// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromomashTask.Infrastructure.Common;

#nullable disable

namespace PromomashTask.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206215722_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromomashTask.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51bc79f6-0c5d-448c-9ce5-1d8fdc15f7c9"),
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("8c315951-198e-47ad-b1eb-b9ca401dc883"),
                            Name = "Country 2"
                        });
                });

            modelBuilder.Entity("PromomashTask.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d73681f-ea00-4d42-a5ab-59eba2d90c5d"),
                            CountryId = new Guid("51bc79f6-0c5d-448c-9ce5-1d8fdc15f7c9"),
                            Name = "Province 1.1"
                        },
                        new
                        {
                            Id = new Guid("5c83ce22-c9aa-48f6-b901-544110b38bdd"),
                            CountryId = new Guid("51bc79f6-0c5d-448c-9ce5-1d8fdc15f7c9"),
                            Name = "Province 1.2"
                        },
                        new
                        {
                            Id = new Guid("2c35eb01-5fe6-4c42-b073-44b3b2c15c90"),
                            CountryId = new Guid("8c315951-198e-47ad-b1eb-b9ca401dc883"),
                            Name = "Province 2.1"
                        },
                        new
                        {
                            Id = new Guid("106b144f-ffd3-4a9f-a029-3c991cd140d5"),
                            CountryId = new Guid("8c315951-198e-47ad-b1eb-b9ca401dc883"),
                            Name = "Province 2.2"
                        });
                });

            modelBuilder.Entity("PromomashTask.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromomashTask.Domain.Entities.Province", b =>
                {
                    b.HasOne("PromomashTask.Domain.Entities.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromomashTask.Domain.Entities.Country", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
